# Contact Information

For general inquiries about the summer school, please contact us at:

- **Email:** TODO

For specific questions, you may also reach out to any member of the [organizing committee](organizers.qmd).

# Location

The event will be held at The Ohio State University, Columbus, OH.

::: {style="width: 100%; height: 350px; margin-top: 1rem;"}
<iframe width="100%" height="350" frameborder="0" style="border:1px solid #aaa; border-radius:12px;" src="https://www.google.com/maps?q=The+Ohio+State+University,+Columbus,+OH&amp;output=embed" allowfullscreen>

</iframe>

<br/>
:::

# Accommodation

Depending on interest, we may be able to offer discounted accommodation through Ohio State's summer on-campus housing programs. To express interest in this option, please check the corresponding box when you submit your application. There are also additional accommodations near campus that you are welcome to book yourself. We recommend The Blackwell (on-campus hotel) or Springhill Suites Columbus OSU (which has a shuttle to campus).

# Travel information


## By air

Columbus is served by John Glenn Columbus International Airport (CMH), located about 6 miles (10 km) from The Ohio State University campus. The airport offers direct flights to many major U.S. cities. Taxis, rideshares, and rental cars are available at the airport.

## By car

Columbus is easily accessible by car via Interstates 70 and 71. The Ohio State University campus is located near the intersection of these major highways. Parking information for the event is to be determined (TBD) and will be provided closer to the workshop dates.
